POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"Prueba",
    "email":"rp@hm.com",
    "password":"123456"
}

###

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"Prueba2",
    "email":"rp2@hm.com",
    "password":"123456"
}

### 

GET http://127.0.0.1:3000/users  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzE3NzY3ODksImV4cCI6MTczMTk5Mjc4OX0.zwsglKLpEcR4yRgEH3weJlN9i-D11ZkV7Ls9t3gHDMY